version: "3.8"
services:
  php:
    build:
      context: .
      dockerfile: .docker/php-fpm/Dockerfile
      target: cli
    stdin_open: true
    volumes:
      - "./:/app:cached"
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "127.0.0.1:8001:8001"
  mariadb:
    image: mariadb:10.6.14
    environment:
      - "MYSQL_ROOT_PASSWORD=vinitela"
      - "MYSQL_USERNAME=medium"
      - "MYSQL_PASSWORD=stories"
      - "MYSQL_DATABASE=medium_event_dispatcher"
    volumes:
      - "db:/var/lib/mysql:delegated"
      - "./.docker/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:delegated"
    healthcheck:
      test: ["CMD-SHELL", "healthcheck.sh --connect"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  db: